-- SolarPro Supabase schema
-- Run this file in Supabase SQL Editor after creating the project.

create extension if not exists pgcrypto;

create table if not exists public.plans (
    slug text primary key,
    name text not null,
    description text not null default '',
    monthly_price numeric not null default 0,
    annual_price numeric not null default 0,
    max_users integer,
    max_projects_per_month integer,
    allow_financial boolean not null default false,
    allow_reports boolean not null default false,
    allow_team_sync boolean not null default true,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.companies (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    document text not null default '',
    plan text not null default 'starter',
    plan_slug text not null default 'starter',
    subscription_status text not null default 'trial',
    trial_ends_at timestamptz,
    subscription_ends_at timestamptz,
    billing_email text not null default '',
    billing_provider text not null default 'manual',
    billing_customer_id text not null default '',
    billing_notes text not null default '',
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    company_id uuid not null references public.companies(id) on delete cascade,
    name text not null,
    matricula text not null default '',
    email text not null default '',
    role text not null default 'usuario',
    permission text not null default 'usuario',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    unique(company_id, matricula)
);

create table if not exists public.subscriptions (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    plan_slug text not null references public.plans(slug),
    status text not null default 'trial',
    provider text not null default 'manual',
    provider_subscription_id text not null default '',
    current_period_start timestamptz,
    current_period_end timestamptz,
    cancel_at_period_end boolean not null default false,
    canceled_at timestamptz,
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.clients (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    name text not null,
    document text not null default '',
    phone text not null default '',
    email text not null default '',
    zip_code text not null default '',
    street text not null default '',
    address_number text not null default '',
    neighborhood text not null default '',
    city text not null default '',
    state text not null default '',
    address_complement text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.budgets (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    client_id bigint not null references public.clients(id) on delete cascade,
    budget_date text not null,
    status text not null default 'Em negociação',
    monthly_consumption numeric not null default 0,
    sun_hours numeric not null default 0,
    monthly_consumptions text not null default '[]',
    monthly_hsp text not null default '[]',
    monthly_generations text not null default '[]',
    monthly_balances text not null default '[]',
    generation_extra_percent numeric not null default 0,
    average_consumption numeric not null default 0,
    average_hsp numeric not null default 0,
    annual_consumption numeric not null default 0,
    annual_generation numeric not null default 0,
    performance_ratio numeric not null default 0,
    module_power numeric not null default 0,
    energy_tariff numeric not null default 0,
    investment numeric not null default 0,
    system_power numeric not null default 0,
    module_count integer not null default 0,
    monthly_generation numeric not null default 0,
    monthly_savings numeric not null default 0,
    payback_years numeric not null default 0,
    down_payment numeric not null default 0,
    monthly_interest_rate numeric not null default 0,
    term_months integer not null default 0,
    financed_amount numeric not null default 0,
    monthly_payment numeric not null default 0,
    total_paid numeric not null default 0,
    total_interest numeric not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.projects (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    client_id bigint not null references public.clients(id) on delete cascade,
    zip_code text not null default '',
    street text not null default '',
    address_number text not null default '',
    neighborhood text not null default '',
    city text not null default '',
    state text not null default '',
    address_complement text not null default '',
    project_date text not null,
    status text not null default 'Em negociação',
    monthly_consumption numeric not null default 0,
    sun_hours numeric not null default 0,
    monthly_consumptions text not null default '[]',
    monthly_hsp text not null default '[]',
    monthly_generations text not null default '[]',
    monthly_balances text not null default '[]',
    generation_extra_percent numeric not null default 0,
    average_consumption numeric not null default 0,
    average_hsp numeric not null default 0,
    annual_consumption numeric not null default 0,
    annual_generation numeric not null default 0,
    performance_ratio numeric not null default 0,
    module_power numeric not null default 0,
    energy_tariff numeric not null default 0,
    project_value numeric not null default 0,
    labor_cost numeric not null default 0,
    module_unit_cost numeric not null default 0,
    inverter_cost numeric not null default 0,
    support_cost numeric not null default 0,
    extra_materials text not null default '[]',
    system_power numeric not null default 0,
    module_count integer not null default 0,
    monthly_generation numeric not null default 0,
    monthly_savings numeric not null default 0,
    payback_years numeric not null default 0,
    down_payment numeric not null default 0,
    monthly_interest_rate numeric not null default 0,
    term_months integer not null default 0,
    financed_amount numeric not null default 0,
    monthly_payment numeric not null default 0,
    total_paid numeric not null default 0,
    total_interest numeric not null default 0,
    payment_type text not null default '',
    discount numeric not null default 0,
    installments_count integer not null default 0,
    installment_value numeric not null default 0,
    first_due_date date,
    financial_notes text not null default '',
    history text not null default '[]',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.project_payments (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    project_id bigint not null references public.projects(id) on delete cascade,
    amount numeric(12,2) not null default 0,
    payment_type text not null default '',
    paid_at timestamptz,
    status text not null default 'paid'
        check (status in ('paid', 'pending', 'canceled')),
    notes text not null default '',
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.project_documents (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    project_id bigint not null references public.projects(id) on delete cascade,
    category text not null default 'Outros',
    original_name text not null default '',
    stored_path text not null default '',
    file_size bigint not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.action_history (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    user_matricula text not null default '',
    user_name text not null default '',
    action text not null,
    entity text not null,
    detail text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.manual_payments (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    subscription_id bigint references public.subscriptions(id) on delete set null,
    amount numeric(12,2) not null default 0,
    currency text not null default 'BRL',
    due_date date,
    paid_at timestamptz,
    status text not null default 'pending'
        check (status in ('pending', 'paid', 'overdue', 'canceled')),
    pix_reference text not null default '',
    receipt_url text not null default '',
    notes text not null default '',
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.beta_feedback (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    profile_id uuid references public.profiles(id) on delete set null,
    rating integer not null default 5 check (rating between 1 and 5),
    area text not null default 'geral'
        check (area in ('geral', 'login', 'crm', 'projetos', 'dimensionamento', 'financeiro', 'sincronizacao', 'visual')),
    message text not null,
    status text not null default 'open'
        check (status in ('open', 'reviewing', 'resolved', 'archived')),
    app_version text not null default 'Solar Pro Mobile 0.1.0',
    device_info text not null default '',
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);

create or replace function public.current_company_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
    select company_id
    from public.profiles
    where id = auth.uid()
      and active = true
    limit 1
$$;

create or replace function public.current_profile_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(permission in ('diretor', 'admin', 'owner'), false)
    from public.profiles
    where id = auth.uid()
      and active = true
    limit 1
$$;

create or replace function public.current_company_plan_slug()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(plan_slug, plan, 'starter')
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_subscription_status()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(subscription_status, 'blocked')
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_subscription_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        case
            when subscription_status = 'active' then true
            when subscription_status = 'trial' then trial_ends_at is null or trial_ends_at >= now()
            else false
        end,
        false
    )
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_monthly_project_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
    select count(*)::integer
    from public.projects
    where company_id = public.current_company_id()
      and created_at >= date_trunc('month', now())
      and created_at < date_trunc('month', now()) + interval '1 month'
$$;

create or replace view public.company_billing_overview
with (security_invoker = true)
as
select
    companies.id as company_id,
    companies.name as company_name,
    companies.plan_slug,
    plans.name as plan_name,
    companies.subscription_status,
    companies.trial_ends_at,
    companies.subscription_ends_at,
    companies.billing_provider,
    plans.monthly_price,
    plans.annual_price,
    plans.max_users,
    plans.max_projects_per_month,
    plans.allow_financial,
    plans.allow_reports,
    plans.allow_team_sync
from public.companies
left join public.plans on plans.slug = companies.plan_slug;

alter table public.plans enable row level security;
alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.clients enable row level security;
alter table public.budgets enable row level security;
alter table public.projects enable row level security;
alter table public.project_payments enable row level security;
alter table public.project_documents enable row level security;
alter table public.action_history enable row level security;
alter table public.manual_payments enable row level security;
alter table public.beta_feedback enable row level security;

drop policy if exists "authenticated users read active plans" on public.plans;
create policy "authenticated users read active plans"
on public.plans for select
to authenticated
using (active = true);

drop policy if exists "users read own company" on public.companies;
create policy "users read own company"
on public.companies for select
to authenticated
using (id = public.current_company_id());

drop policy if exists "users read profiles from own company" on public.profiles;
create policy "users read profiles from own company"
on public.profiles for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "admins manage profiles from own company" on public.profiles;
create policy "admins manage profiles from own company"
on public.profiles for all
to authenticated
using (company_id = public.current_company_id() and public.current_profile_is_admin())
with check (company_id = public.current_company_id() and public.current_profile_is_admin());

drop policy if exists "users read subscriptions from own company" on public.subscriptions;
create policy "users read subscriptions from own company"
on public.subscriptions for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "admins manage subscriptions from own company" on public.subscriptions;
create policy "admins manage subscriptions from own company"
on public.subscriptions for all
to authenticated
using (company_id = public.current_company_id() and public.current_profile_is_admin())
with check (company_id = public.current_company_id() and public.current_profile_is_admin());

drop policy if exists "users manage clients from own company" on public.clients;
create policy "users manage clients from own company"
on public.clients for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

drop policy if exists "users manage budgets from own company" on public.budgets;
create policy "users manage budgets from own company"
on public.budgets for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

drop policy if exists "users manage projects from own company" on public.projects;
create policy "users manage projects from own company"
on public.projects for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

drop policy if exists "users manage project payments from own company" on public.project_payments;
create policy "users manage project payments from own company"
on public.project_payments for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

drop policy if exists "users manage project documents from own company" on public.project_documents;
create policy "users manage project documents from own company"
on public.project_documents for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

drop policy if exists "users read history from own company" on public.action_history;
create policy "users read history from own company"
on public.action_history for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "users insert history from own company" on public.action_history;
create policy "users insert history from own company"
on public.action_history for insert
to authenticated
with check (company_id = public.current_company_id());

drop policy if exists "users read manual payments from own company" on public.manual_payments;
create policy "users read manual payments from own company"
on public.manual_payments for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "admins manage manual payments from own company" on public.manual_payments;
create policy "admins manage manual payments from own company"
on public.manual_payments for all
to authenticated
using (company_id = public.current_company_id() and public.current_profile_is_admin())
with check (company_id = public.current_company_id() and public.current_profile_is_admin());

drop policy if exists "users read feedback from own company" on public.beta_feedback;
create policy "users read feedback from own company"
on public.beta_feedback for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "users insert feedback from own company" on public.beta_feedback;
create policy "users insert feedback from own company"
on public.beta_feedback for insert
to authenticated
with check (
    company_id = public.current_company_id()
    and (profile_id is null or profile_id = auth.uid())
);

drop policy if exists "admins update feedback from own company" on public.beta_feedback;
create policy "admins update feedback from own company"
on public.beta_feedback for update
to authenticated
using (company_id = public.current_company_id() and public.current_profile_is_admin())
with check (company_id = public.current_company_id() and public.current_profile_is_admin());

create index if not exists idx_companies_plan_slug on public.companies(plan_slug);
create index if not exists idx_companies_subscription_status on public.companies(subscription_status);
create index if not exists idx_profiles_company_id on public.profiles(company_id);
create index if not exists idx_subscriptions_company_id on public.subscriptions(company_id);
create index if not exists idx_subscriptions_status on public.subscriptions(status);
create index if not exists idx_clients_company_id on public.clients(company_id);
create index if not exists idx_budgets_company_id on public.budgets(company_id);
create index if not exists idx_budgets_client_id on public.budgets(client_id);
create index if not exists idx_projects_company_id on public.projects(company_id);
create index if not exists idx_projects_client_id on public.projects(client_id);
create index if not exists idx_project_payments_company_id on public.project_payments(company_id);
create index if not exists idx_project_payments_project_id on public.project_payments(project_id);
create index if not exists idx_project_payments_status on public.project_payments(status);
create index if not exists idx_project_payments_paid_at on public.project_payments(paid_at desc);
create index if not exists idx_project_documents_company_id on public.project_documents(company_id);
create index if not exists idx_project_documents_project_id on public.project_documents(project_id);
create index if not exists idx_project_documents_category on public.project_documents(category);
create index if not exists idx_action_history_company_id on public.action_history(company_id);
create index if not exists idx_manual_payments_company_id on public.manual_payments(company_id);
create index if not exists idx_manual_payments_status on public.manual_payments(status);
create index if not exists idx_manual_payments_due_date on public.manual_payments(due_date);
create index if not exists idx_beta_feedback_company_id on public.beta_feedback(company_id);
create index if not exists idx_beta_feedback_status on public.beta_feedback(status);
create index if not exists idx_beta_feedback_created_at on public.beta_feedback(created_at desc);

-- P2.1: Composite indexes for common query patterns (dual filters)
create index if not exists idx_projects_company_status on public.projects(company_id, status);
create index if not exists idx_manual_payments_company_due_date on public.manual_payments(company_id, due_date);
create index if not exists idx_project_payments_company_paid_at on public.project_payments(company_id, paid_at desc);
create index if not exists idx_clients_company_name on public.clients(company_id, name);
create index if not exists idx_budgets_company_status on public.budgets(company_id, status);

insert into public.plans (
    slug,
    name,
    description,
    monthly_price,
    annual_price,
    max_users,
    max_projects_per_month,
    allow_financial,
    allow_reports,
    allow_team_sync
)
values
    (
        'starter',
        'Starter',
        'Plano para profissional solo ou pequena operacao.',
        39.90,
        399.00,
        1,
        30,
        false,
        false,
        true
    ),
    (
        'equipe',
        'Equipe',
        'Plano para empresas pequenas e empresas junior.',
        99.90,
        999.00,
        5,
        null,
        true,
        false,
        true
    ),
    (
        'pro',
        'Pro',
        'Plano para operacoes maiores com recursos avancados.',
        199.90,
        1999.00,
        15,
        null,
        true,
        true,
        true
    )
on conflict (slug) do update set
    name = excluded.name,
    description = excluded.description,
    monthly_price = excluded.monthly_price,
    annual_price = excluded.annual_price,
    max_users = excluded.max_users,
    max_projects_per_month = excluded.max_projects_per_month,
    allow_financial = excluded.allow_financial,
    allow_reports = excluded.allow_reports,
    allow_team_sync = excluded.allow_team_sync,
    active = true,
    updated_at = now();

insert into public.projects (
    id,
    company_id,
    client_id,
    project_date,
    status,
    monthly_consumption,
    sun_hours,
    monthly_consumptions,
    monthly_hsp,
    monthly_generations,
    monthly_balances,
    generation_extra_percent,
    average_consumption,
    average_hsp,
    annual_consumption,
    annual_generation,
    performance_ratio,
    module_power,
    energy_tariff,
    project_value,
    system_power,
    module_count,
    monthly_generation,
    monthly_savings,
    payback_years,
    down_payment,
    monthly_interest_rate,
    term_months,
    financed_amount,
    monthly_payment,
    total_paid,
    total_interest,
    history,
    created_at,
    updated_at
)
select
    budgets.id,
    budgets.company_id,
    budgets.client_id,
    budgets.budget_date,
    budgets.status,
    budgets.monthly_consumption,
    budgets.sun_hours,
    budgets.monthly_consumptions,
    budgets.monthly_hsp,
    budgets.monthly_generations,
    budgets.monthly_balances,
    budgets.generation_extra_percent,
    budgets.average_consumption,
    budgets.average_hsp,
    budgets.annual_consumption,
    budgets.annual_generation,
    budgets.performance_ratio,
    budgets.module_power,
    budgets.energy_tariff,
    budgets.investment,
    budgets.system_power,
    budgets.module_count,
    budgets.monthly_generation,
    budgets.monthly_savings,
    budgets.payback_years,
    budgets.down_payment,
    budgets.monthly_interest_rate,
    budgets.term_months,
    budgets.financed_amount,
    budgets.monthly_payment,
    budgets.total_paid,
    budgets.total_interest,
    '[]',
    budgets.created_at,
    budgets.updated_at
from public.budgets
where not exists (
    select 1
    from public.projects
    where projects.id = budgets.id
)
on conflict (id) do nothing;

select setval(
    pg_get_serial_sequence('public.projects', 'id'),
    coalesce((select max(id) from public.projects), 1),
    true
);

create table if not exists public.app_messages (
    id bigserial primary key,
    company_id uuid not null references public.companies(id) on delete cascade,
    payment_id bigint references public.manual_payments(id) on delete set null,
    title text not null,
    message text not null,
    type text not null default 'info'
        check (type in ('info', 'billing', 'warning', 'success')),
    status text not null default 'unread'
        check (status in ('unread', 'read', 'archived')),
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    read_at timestamptz,
    expires_at timestamptz
);

create index if not exists idx_app_messages_company_id
on public.app_messages(company_id);

create index if not exists idx_app_messages_status
on public.app_messages(status);

create index if not exists idx_app_messages_created_at
on public.app_messages(created_at desc);

create index if not exists idx_app_messages_payment_id
on public.app_messages(payment_id);

alter table public.app_messages enable row level security;

drop policy if exists "users read messages from own company" on public.app_messages;
create policy "users read messages from own company"
on public.app_messages for select
to authenticated
using (
    company_id = public.current_company_id()
    and (expires_at is null or expires_at >= now())
);

drop policy if exists "users update own company message status" on public.app_messages;
create policy "users update own company message status"
on public.app_messages for update
to authenticated
using (company_id = public.current_company_id())
with check (
    company_id = public.current_company_id()
    and status in ('read', 'archived')
);

drop policy if exists "admins create messages for own company" on public.app_messages;
create policy "admins create messages for own company"
on public.app_messages for insert
to authenticated
with check (
    company_id = public.current_company_id()
    and public.current_profile_is_admin()
);

drop policy if exists "users create follow up messages from own company"
on public.app_messages;
create policy "users create follow up messages from own company"
on public.app_messages for insert
to authenticated
with check (
    company_id = public.current_company_id()
    and payment_id is null
    and type = 'warning'
    and status = 'unread'
    and title = 'Follow-up sugerido'
    and created_by = auth.uid()
);
