-- SolarPro project architecture migration
-- Creates the canonical projects table and copies legacy budgets when present.

create table if not exists public.projects (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    client_id bigint not null references public.clients(id) on delete cascade,
    project_date text not null,
    status text not null default 'Em negociação',
    monthly_consumption numeric not null default 0,
    sun_hours numeric not null default 0,
    monthly_consumptions text not null default '[]',
    monthly_hsp text not null default '[]',
    monthly_generations text not null default '[]',
    monthly_balances text not null default '[]',
    generation_extra_percent numeric not null default 0,
    average_consumption numeric not null default 0,
    average_hsp numeric not null default 0,
    annual_consumption numeric not null default 0,
    annual_generation numeric not null default 0,
    performance_ratio numeric not null default 0,
    module_power numeric not null default 0,
    energy_tariff numeric not null default 0,
    project_value numeric not null default 0,
    system_power numeric not null default 0,
    module_count integer not null default 0,
    monthly_generation numeric not null default 0,
    monthly_savings numeric not null default 0,
    payback_years numeric not null default 0,
    down_payment numeric not null default 0,
    monthly_interest_rate numeric not null default 0,
    term_months integer not null default 0,
    financed_amount numeric not null default 0,
    monthly_payment numeric not null default 0,
    total_paid numeric not null default 0,
    total_interest numeric not null default 0,
    history text not null default '[]',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.projects enable row level security;

drop policy if exists "users manage projects from own company" on public.projects;
create policy "users manage projects from own company"
on public.projects for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

create index if not exists idx_projects_company_id on public.projects(company_id);
create index if not exists idx_projects_client_id on public.projects(client_id);

insert into public.projects (
    id,
    company_id,
    client_id,
    project_date,
    status,
    monthly_consumption,
    sun_hours,
    monthly_consumptions,
    monthly_hsp,
    monthly_generations,
    monthly_balances,
    generation_extra_percent,
    average_consumption,
    average_hsp,
    annual_consumption,
    annual_generation,
    performance_ratio,
    module_power,
    energy_tariff,
    project_value,
    system_power,
    module_count,
    monthly_generation,
    monthly_savings,
    payback_years,
    down_payment,
    monthly_interest_rate,
    term_months,
    financed_amount,
    monthly_payment,
    total_paid,
    total_interest,
    history,
    created_at,
    updated_at
)
select
    budgets.id,
    budgets.company_id,
    budgets.client_id,
    budgets.budget_date,
    budgets.status,
    budgets.monthly_consumption,
    budgets.sun_hours,
    budgets.monthly_consumptions,
    budgets.monthly_hsp,
    budgets.monthly_generations,
    budgets.monthly_balances,
    budgets.generation_extra_percent,
    budgets.average_consumption,
    budgets.average_hsp,
    budgets.annual_consumption,
    budgets.annual_generation,
    budgets.performance_ratio,
    budgets.module_power,
    budgets.energy_tariff,
    budgets.investment,
    budgets.system_power,
    budgets.module_count,
    budgets.monthly_generation,
    budgets.monthly_savings,
    budgets.payback_years,
    budgets.down_payment,
    budgets.monthly_interest_rate,
    budgets.term_months,
    budgets.financed_amount,
    budgets.monthly_payment,
    budgets.total_paid,
    budgets.total_interest,
    '[]',
    budgets.created_at,
    budgets.updated_at
from public.budgets
where to_regclass('public.budgets') is not null
  and not exists (
      select 1
      from public.projects
      where projects.id = budgets.id
  )
on conflict (id) do nothing;

select setval(
    pg_get_serial_sequence('public.projects', 'id'),
    coalesce((select max(id) from public.projects), 1),
    true
);
