-- SolarPro commercial subscription foundation.
-- Week 2: plans, subscriptions, company billing fields, limits and helper functions.

create table if not exists public.plans (
    slug text primary key,
    name text not null,
    description text not null default '',
    monthly_price numeric not null default 0,
    annual_price numeric not null default 0,
    max_users integer,
    max_projects_per_month integer,
    allow_financial boolean not null default false,
    allow_reports boolean not null default false,
    allow_team_sync boolean not null default true,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.plans (
    slug,
    name,
    description,
    monthly_price,
    annual_price,
    max_users,
    max_projects_per_month,
    allow_financial,
    allow_reports,
    allow_team_sync
)
values
    (
        'starter',
        'Starter',
        'Plano para profissional solo ou pequena operacao.',
        39.90,
        399.00,
        1,
        30,
        false,
        false,
        true
    ),
    (
        'equipe',
        'Equipe',
        'Plano para empresas pequenas e empresas junior.',
        99.90,
        999.00,
        5,
        null,
        true,
        false,
        true
    ),
    (
        'pro',
        'Pro',
        'Plano para operacoes maiores com recursos avancados.',
        199.90,
        1999.00,
        15,
        null,
        true,
        true,
        true
    )
on conflict (slug) do update set
    name = excluded.name,
    description = excluded.description,
    monthly_price = excluded.monthly_price,
    annual_price = excluded.annual_price,
    max_users = excluded.max_users,
    max_projects_per_month = excluded.max_projects_per_month,
    allow_financial = excluded.allow_financial,
    allow_reports = excluded.allow_reports,
    allow_team_sync = excluded.allow_team_sync,
    active = true,
    updated_at = now();

alter table public.companies
    add column if not exists plan_slug text not null default 'starter',
    add column if not exists subscription_status text not null default 'trial',
    add column if not exists trial_ends_at timestamptz,
    add column if not exists subscription_ends_at timestamptz,
    add column if not exists billing_email text not null default '',
    add column if not exists billing_provider text not null default 'manual',
    add column if not exists billing_customer_id text not null default '',
    add column if not exists billing_notes text not null default '';

update public.companies
set plan_slug = coalesce(nullif(plan, ''), 'starter')
where plan_slug = 'starter'
  and coalesce(nullif(plan, ''), 'starter') <> plan_slug;

update public.companies
set trial_ends_at = coalesce(trial_ends_at, created_at + interval '14 days')
where subscription_status = 'trial';

create table if not exists public.subscriptions (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    plan_slug text not null references public.plans(slug),
    status text not null default 'trial',
    provider text not null default 'manual',
    provider_subscription_id text not null default '',
    current_period_start timestamptz,
    current_period_end timestamptz,
    cancel_at_period_end boolean not null default false,
    canceled_at timestamptz,
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.subscriptions (
    company_id,
    plan_slug,
    status,
    provider,
    current_period_start,
    current_period_end,
    notes
)
select
    companies.id,
    companies.plan_slug,
    companies.subscription_status,
    companies.billing_provider,
    companies.created_at,
    coalesce(companies.subscription_ends_at, companies.trial_ends_at),
    'Assinatura inicial criada pela migration comercial.'
from public.companies
where not exists (
    select 1
    from public.subscriptions
    where subscriptions.company_id = companies.id
);

create or replace function public.current_company_plan_slug()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(plan_slug, plan, 'starter')
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_subscription_status()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(subscription_status, 'blocked')
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_subscription_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        case
            when subscription_status = 'active' then true
            when subscription_status = 'trial' then trial_ends_at is null or trial_ends_at >= now()
            else false
        end,
        false
    )
    from public.companies
    where id = public.current_company_id()
    limit 1
$$;

create or replace function public.current_company_monthly_project_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
    select count(*)::integer
    from public.projects
    where company_id = public.current_company_id()
      and created_at >= date_trunc('month', now())
      and created_at < date_trunc('month', now()) + interval '1 month'
$$;

create or replace view public.company_billing_overview
with (security_invoker = true)
as
select
    companies.id as company_id,
    companies.name as company_name,
    companies.plan_slug,
    plans.name as plan_name,
    companies.subscription_status,
    companies.trial_ends_at,
    companies.subscription_ends_at,
    companies.billing_provider,
    plans.monthly_price,
    plans.annual_price,
    plans.max_users,
    plans.max_projects_per_month,
    plans.allow_financial,
    plans.allow_reports,
    plans.allow_team_sync
from public.companies
left join public.plans on plans.slug = companies.plan_slug;

alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;

drop policy if exists "authenticated users read active plans" on public.plans;
create policy "authenticated users read active plans"
on public.plans for select
to authenticated
using (active = true);

drop policy if exists "users read subscriptions from own company" on public.subscriptions;
create policy "users read subscriptions from own company"
on public.subscriptions for select
to authenticated
using (company_id = public.current_company_id());

drop policy if exists "admins manage subscriptions from own company" on public.subscriptions;
create policy "admins manage subscriptions from own company"
on public.subscriptions for all
to authenticated
using (company_id = public.current_company_id() and public.current_profile_is_admin())
with check (company_id = public.current_company_id() and public.current_profile_is_admin());

create index if not exists idx_companies_plan_slug on public.companies(plan_slug);
create index if not exists idx_companies_subscription_status on public.companies(subscription_status);
create index if not exists idx_subscriptions_company_id on public.subscriptions(company_id);
create index if not exists idx_subscriptions_status on public.subscriptions(status);
