alter table public.projects
    add column if not exists payment_type text not null default '',
    add column if not exists discount numeric not null default 0,
    add column if not exists installments_count integer not null default 0,
    add column if not exists installment_value numeric not null default 0,
    add column if not exists first_due_date date,
    add column if not exists financial_notes text not null default '';

create table if not exists public.project_payments (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    project_id bigint not null references public.projects(id) on delete cascade,
    amount numeric(12,2) not null default 0,
    payment_type text not null default '',
    paid_at timestamptz,
    status text not null default 'paid'
        check (status in ('paid', 'pending', 'canceled')),
    notes text not null default '',
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.project_payments enable row level security;

drop policy if exists "users manage project payments from own company" on public.project_payments;
create policy "users manage project payments from own company"
on public.project_payments for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

create index if not exists idx_project_payments_company_id on public.project_payments(company_id);
create index if not exists idx_project_payments_project_id on public.project_payments(project_id);
create index if not exists idx_project_payments_status on public.project_payments(status);
create index if not exists idx_project_payments_paid_at on public.project_payments(paid_at desc);

