-- SolarPro: project document metadata for offline-first sync.

create table if not exists public.project_documents (
    id bigint primary key generated by default as identity,
    company_id uuid not null references public.companies(id) on delete cascade,
    project_id bigint not null references public.projects(id) on delete cascade,
    category text not null default 'Outros',
    original_name text not null default '',
    stored_path text not null default '',
    file_size bigint not null default 0,
    created_at timestamptz not null default now()
);

alter table public.project_documents enable row level security;

drop policy if exists "users manage project documents from own company" on public.project_documents;
create policy "users manage project documents from own company"
on public.project_documents for all
to authenticated
using (company_id = public.current_company_id())
with check (company_id = public.current_company_id());

create index if not exists idx_project_documents_company_id on public.project_documents(company_id);
create index if not exists idx_project_documents_project_id on public.project_documents(project_id);
create index if not exists idx_project_documents_category on public.project_documents(category);
